### ISSUE TITLE
May I know when I can access the source code of EulerFormer?

### ISSUE THREAD

**Issue by VanillaCreamer** [Ethan-TZ/EulerFormer#1]
I am very interested in your method. May I know when I can see your paper and source code？

**Comment by Ethan-TZ** [comment]
@manjusaka-L  Hello, we have uploaded the paper in advance on GitHub. We are also working hard to organize the code and expect to have it sorted out by tomorrow.

**Comment by Ethan-TZ** [comment]
@manjusaka-L We have updated our code.

**Comment by VanillaCreamer** [comment]
Thanks a lot!!!
